### ISSUE TITLE
License and how to run this project?

### ISSUE THREAD

**Issue by tomtom215** [WecoAI/aideml#1]
Hi all,

Just came across this from [an article](https://www.marktechpost.com/2024/04/05/weco-ai-unveils-aide-an-ai-agent-that-can-automatically-solve-data-science-tasks-at-a-human-level/) but I don't see a license on this repo nor a way documentation on how to try this project out. 

Looking forward to an update and trying this out in the future!

**Comment by ZhengyaoJiang** [comment]
Hey, the open sourcing will arrive before the end of April. Before that, feel free to register our waitlist to get early access to the cloud hosted version: https://www.weco.ai/

Btw, in case that's helpful our official tech report is at: https://www.weco.ai/blog/technical-report
