### ISSUE TITLE
Does aideml supports Windows?

### ISSUE THREAD

**Issue by Okaya20** [WecoAI/aideml#16]
Hi,

When i am trying to run it via windows, it is giving me this bug:

{
	"name": "PermissionError",
	"message": "[WinError 5] Access denied",
	"stack": "---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
File c:\\Users\\Hp\\Desktop\\AIDE\\venv\\Lib\\site-packages\\aide\\interpreter.py:236, in Interpreter.run(self, code, reset_session)
    234 try:
    235     # check if the child is done
--> 236     state = self.event_outq.get(timeout=1)  # wait for state:finished
    237     assert state[0] == \"state:finished\", state

File ~\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\multiprocessing\\queues.py:114, in Queue.get(self, block, timeout)
    113     if not self._poll(timeout):
--> 114         raise Empty
    115 elif not self._poll():

Empty: 

During handling of the above exception, another exception occurred:

PermissionError                           Traceback (most recent call last)
Cell In[8], line 7
      1 exp = aide.Experiment(
      2     data_dir=\"data_dir\",  # replace this with your own directory
      3     goal=mygoal,  # replace with your own goal description
      4     eval=\"MAPE\"  # replace with your own evaluation metric
      5 )
----> 7 best_solution = exp.run(steps=25)
      9 print(f\"Best solution has validation metric: {best_solution.valid_metric}\")
     10 print(f\"Best solution code: {best_solution.code}\")

File c:\\Users\\Hp\\Desktop\\AIDE\\venv\\Lib\\site-packages\\aide\\__init__.py:52, in Experiment.run(self, steps)
     50 def run(self, steps: int) -> Solution:
     51     for _i in range(steps):
---> 52         self.agent.step(exec_callback=self.interpreter.run)
     53         save_run(self.cfg, self.journal)
     54     self.interpreter.cleanup_session()

File c:\\Users\\Hp\\Desktop\\AIDE\\venv\\Lib\\site-packages\\aide\\agent.py:292, in Agent.step(self, exec_callback)
    287 else:
    288     result_node = self._improve(parent_node)
    290 self.parse_exec_result(
    291     node=result_node,
--> 292     exec_result=exec_callback(result_node.code, True),
    293 )
    294 self.journal.append(result_node)

File c:\\Users\\Hp\\Desktop\\AIDE\\venv\\Lib\\site-packages\\aide\\interpreter.py:261, in Interpreter.run(self, code, reset_session)
    258 assert reset_session, \"Timeout ocurred in interactive session\"
    260 # send interrupt to child
--> 261 os.kill(self.process.pid, signal.SIGINT)  # type: ignore
    262 child_in_overtime = True
    263 # terminate if we're overtime by more than a minute

PermissionError: [WinError 5] Access denied"
}
i think this is about "os.kill(self.process.pid, signal.SIGINT)"  line 
i dont think this works with  windows.

**Comment by dexhunter** [comment]
Can you run with docker? https://github.com/WecoAI/aideml/pull/18/files

**Comment by dexhunter** [comment]
You should be able to run on Windows with Docker now but let me know if any issues persist
