### ISSUE TITLE
How to use Anthropic Claude?

### ISSUE THREAD

**Issue by edangx100** [WecoAI/aideml#2]
I had performed the step of export the Anthropic key as stated in README file.
But i am still prompted to use OpenAI key. 
How can i use  Anthropic Claude and not OpenAI?

**Comment by schmidtdominik** [comment]
You can use the `agent.code.model=...` argument to use a Claude model for the coding step, however the execution feedback step currently only supports the OpenAI API (for function calling) so you will still need to provide an API key for that.

**Comment by edangx100** [comment]
I tried this as what you described in config.yaml.
Both Claude and OpenAI keys are then exported as stated in README.

But in execution of Aide,  only OpenAI model is used for both coding as well as execution feedback

How to use Claude model here?

**Comment by crazydevlegend** [comment]
> I tried what you described (`agent.code.model=..`) at file 'config.yaml'. Both Claude and OpenAI keys are then exported as suggested from README.
> 
> But when i run (Aide), only OpenAI model is used for both (1) coding as well as (2) execution feedback. Claude model was not used.
> 
> How to use Claude model here?

can you plz show me what your config looks like.
- `config.yaml` file
- `cfg` object in `run.py`

**Comment by dexhunter** [comment]
I just tried with models from Anthropic, as long as model names are correct, one should be able to run. You can double-check model names from [here](https://docs.anthropic.com/en/docs/about-claude/models)
