### ISSUE TITLE
GPU Requirements?

### ISSUE THREAD

**Issue by TonyTeng66** [WecoAI/aideml#22]
Hi!

I have read through README and found the requirements for GPU are not specified. Is there a minimum amount of graphic memory for the GPU? Also, how much time would it take to get the results for one task? 

Thank you for this great repo.

Best,
Xin

**Comment by dexhunter** [comment]
>  Is there a minimum amount of graphic memory for the GPU? 

GPU is not specifically needed, as long as you have access to LLM, you are good to go

>  how much time would it take to get the results for one task?

It depends on how many methods (steps) you want to search and the size of your task

**Comment by TonyTeng66** [comment]
I see. Thank you!
