### ISSUE TITLE
Question: How to use OpenAI base URL?

### ISSUE THREAD

**Issue by syaikhipin** [WecoAI/aideml#3]
I have a question regarding the usage of the OpenAI base URL in the aideml project. Can someone provide guidance on how to properly configure and utilize the OpenAI base URL within the project?

Any information or examples would be greatly appreciated. Thank you!

**Comment by schmidtdominik** [comment]
If you want to use an alternative backend URL, you can set the `OPENAI_BASE_URL` env variable by running `export OPENAI_BASE_URL="..."` before running AIDE.
