### ISSUE TITLE
How to reproduce Kaggle Result on "Classification with a Tabular Vector Borne Disease Dataset"

### ISSUE THREAD

**Issue by Innixma** [WecoAI/aideml#4]
Hello!

In the table of results in the readme, it lists the private leaderboard percentile achieved in each Kaggle competition as well as a link to the code to reproduce it and the competition to apply the code to.

I took one of the code solutions with the strongest performance claim (**Top 0%**), which is for the dataset "Predict disease prognosis" in the table. I then copy pasted that code into Kaggle for the given competition, and clicked "Run and Submit".

I got a private leaderboard score of `0.42872`, which places in `Rank 619 of 934` competitors, or **Top 66%**.

Can the authors clarify what I did wrong and how I can get the claimed top 0% private leaderboard result?

Kaggle Notebook running AIDEML's code solution: https://www.kaggle.com/code/innixma/aideml-test
AIDEML Code Solution on GitHub: https://github.com/WecoAI/aideml/blob/main/sample_results/playground-series-s3e13.py
Kaggle Competition: https://www.kaggle.com/competitions/playground-series-s3e13

Looking forward to hearing back!

**Comment by ZhengyaoJiang** [comment]
Hi,
Many thanks for flagging this!
We're using an automated evaluation pipeline, and the top% is a noisy estimation of the private leaderboard position. The noise come from that some tasks do not allow late submissions to the private leaderboard, and, as far as we know, there is no API for the private leaderboard performance distribution. However, generally the mean performance of these 60 competitions should match the top 50% claim.

As for the task you mentioned, 0% definitely means it's an overestimated one, but the noise shouldn't be large enough to push the score from 0% to 66%. A private leaderboard score of 0.42 is on the lower end of the 12 submissions we tested. The private scores are `0.46271, 0.44956, 0.47258, 0.45833, 0.44407, 0.48684, 0.40679, 0.46271, 0.45065, 0.48684, 0.33881, 0.48026`.

We believe there might be something wrong in the pipeline where we fetched the code listed in this repo. We'll investigate this and update the code gallery accordingly.

**Comment by Innixma** [comment]
Thanks!

> as far as we know, there is no API for the private leaderboard performance distribution

You can access this information via https://www.kaggle.com/datasets/kaggle/meta-kaggle

It would be good to clarify within the technical report that the results are not true private leaderboard percentiles, as well as the method in which the noisy estimation is computed. Given the significance of the claim in the technical report, I think it may warrant manual submission of the submission.csv files for the competitions that you are unable to automatically submit to, to ensure that the correct private leaderboard percentiles are being reported for reproducibility when combined with the code solution scripts.

Additionally, info on how the baseline methods such as H2O were ran, including example scripts for how to reproduce the results obtained with them, would be useful.

> A private leaderboard score of 0.42 is on the lower end of the 12 submissions we tested. The private scores are 0.46271, 0.44956, 0.47258, 0.45833, 0.44407, 0.48684, 0.40679, 0.46271, 0.45065, 0.48684, 0.33881, 0.48026

How did you determine which of the 12 submissions to report in your results table, and how did you decide on 12 submissions?

**Comment by ZhengyaoJiang** [comment]
Hi,
Regarding benchmark the way we compute the scores is rather complex, but we will describe it in the next version of the tech report. We do have plan to release a simpler and unified benchmark for the community to run evaluation by themselves!

> Given the significance of the claim in the technical report, I think it may warrant manual submission of the submission.csv files for the competitions that you are unable to automatically submit to

It's not about unable to automatically submit but wether the competition shows the private leaderboard scores for late submissions.

> You can access this information via https://www.kaggle.com/datasets/kaggle/meta-kaggle

Yes, we did use Meta Kaggle, but it doesn't include private scores for all the competitions we tested, possibly due to licensing issues. Additionally, the submission scores aren't aggregated by teams, so they differ from what's shown on the website.

> A private leaderboard score of 0.42 is on the lower end of the 12 submissions we tested. The private scores are 0.46271, 0.44956, 0.47258, 0.45833, 0.44407, 0.48684, 0.40679, 0.46271, 0.45065, 0.48684, 0.33881, 0.48026

These scores are based on the agent's own cross-validation evaluation. To the point, we're not cherrypicking the highest private leaderboard scores.

**Comment by usamimeri** [comment]
@ZhengyaoJiang 
Hello! I am trying to reproduce all aideml solutions on Kaggle and plan to write a blog comparing some AutoML packages. However, running aideml with GPT-4-turbo is costing me a lot. So, I am wondering if you can provide the detailed scores corresponding to each solution as some Top% may affected by noise.
